---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${PID}
      - PGID=${GID}
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${STORAGE_PATH}/Downloads:/downloads
      - ${STORAGE_PATH}/Videos:/videos
    restart: unless-stopped
