---
version: "3.9"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PID}
      - PGID=${GID}
      - TZ=Europe/Stockholm
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ${CONFIG_PATH}/jackett:/config
      - ${STORAGE_PATH}/Downloads:/downloads
    # ports:
      # - 9117:9117
    network_mode: container:gluetun
    restart: unless-stopped
