---
version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PID}:${GID}
    group_add:
      - 44 # video group so that we have access to hw accel
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${STORAGE_PATH}:/storage
      - /opt/vc/lib:/opt/vc/lib # rpi openmax lib path
    ports:
      - 8096:8096 # http webui
      - 8920:8920 # https webui (need to setup ssl)
      - 7359:7359/udp # allow clients to discover jellyfin
      - 1900:1900/udp # discover by DNLA and clients
    devices:
      - /dev/dri:/dev/dri # intel hw accel (vaapi)
      - /dev/vcsm-cma:/dev/vcsm-cma # rpi openmax video decoding
      - /dev/vchiq:/dev/vchiq # rpi openmax video encoding
      - /dev/video10:/dev/video10 # rpi v4l2 video encoding
      - /dev/video11:/dev/video11 # rpi v412 video encoding
      - /dev/video12:/dev/video12 # rpi v4l2 video encoding
      # note that nvidia hwaccel requires more setup
    restart: unless-stopped
