---
version: "3.9"
services:
  samba:
    image: dperson/samba
    environment:
      USERID: ${PID}
      GROUPID: ${GID}
      TZ: Europe/Stockholm
    volumes:
      - ${CONFIG_PATH}/samba:/config
      - ${STORAGE_PATH}:/storage
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp" 
    restart: unless-stopped
    command: " -s \"Storage;/storage;yes;no;no;${SMB_USER_NAME}\" -u \"${SMB_USER_NAME};${SMB_PASSWORD}\" -p"

