---
version: "3.9"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PID}
      - PGID=${GID}
      - TZ=Europe/Stockholm
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${STORAGE_PATH}:/storage
    ports:
      - 8989:8989
    restart: unless-stopped
